classes.dir=target/classes
component.inlineBindingPrefix=$
component.inlineBindingSuffix=
component.wellFormedTemplateRequired=false
customInfoPListContent=
principalClass=app.AppLauncher
project.name=Vacation
project.name.lowercase=vacation
project.type=application
webXML=false
webXML_CustomContent=
project.base=wo
