package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.LocalTime;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.CalendarEvent;
import vacation.data.DrivingRoute;
import vacation.data.Spot;
import vacation.data.Trip;

/**
 * Class _CalendarEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CalendarEvent extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<CalendarEvent> SELF = PropertyFactory.createSelf(CalendarEvent.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "CalendarEvent", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final DateProperty<LocalDate> END = PropertyFactory.createDate("end", LocalDate.class);
    public static final DateProperty<LocalTime> END_TIME = PropertyFactory.createDate("endTime", LocalTime.class);
    public static final StringProperty<String> PERSON = PropertyFactory.createString("person", String.class);
    public static final DateProperty<LocalDate> START = PropertyFactory.createDate("start", LocalDate.class);
    public static final DateProperty<LocalTime> START_TIME = PropertyFactory.createDate("startTime", LocalTime.class);
    public static final StringProperty<String> TITLE = PropertyFactory.createString("title", String.class);
    public static final EntityProperty<DrivingRoute> ROUTE = PropertyFactory.createEntity("route", DrivingRoute.class);
    public static final EntityProperty<Spot> SPOT = PropertyFactory.createEntity("spot", Spot.class);
    public static final EntityProperty<Trip> TRIP = PropertyFactory.createEntity("trip", Trip.class);

    protected String description;
    protected LocalDate end;
    protected LocalTime endTime;
    protected String person;
    protected LocalDate start;
    protected LocalTime startTime;
    protected String title;

    protected Object route;
    protected Object spot;
    protected Object trip;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String description() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setEnd(LocalDate end) {
        beforePropertyWrite("end", this.end, end);
        this.end = end;
    }

    public LocalDate end() {
        beforePropertyRead("end");
        return this.end;
    }

    public void setEndTime(LocalTime endTime) {
        beforePropertyWrite("endTime", this.endTime, endTime);
        this.endTime = endTime;
    }

    public LocalTime endTime() {
        beforePropertyRead("endTime");
        return this.endTime;
    }

    public void setPerson(String person) {
        beforePropertyWrite("person", this.person, person);
        this.person = person;
    }

    public String person() {
        beforePropertyRead("person");
        return this.person;
    }

    public void setStart(LocalDate start) {
        beforePropertyWrite("start", this.start, start);
        this.start = start;
    }

    public LocalDate start() {
        beforePropertyRead("start");
        return this.start;
    }

    public void setStartTime(LocalTime startTime) {
        beforePropertyWrite("startTime", this.startTime, startTime);
        this.startTime = startTime;
    }

    public LocalTime startTime() {
        beforePropertyRead("startTime");
        return this.startTime;
    }

    public void setTitle(String title) {
        beforePropertyWrite("title", this.title, title);
        this.title = title;
    }

    public String title() {
        beforePropertyRead("title");
        return this.title;
    }

    public void setRoute(DrivingRoute route) {
        setToOneTarget("route", route, true);
    }

    public DrivingRoute route() {
        return (DrivingRoute)readProperty("route");
    }

    public void setSpot(Spot spot) {
        setToOneTarget("spot", spot, true);
    }

    public Spot spot() {
        return (Spot)readProperty("spot");
    }

    public void setTrip(Trip trip) {
        setToOneTarget("trip", trip, true);
    }

    public Trip trip() {
        return (Trip)readProperty("trip");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "end":
                return this.end;
            case "endTime":
                return this.endTime;
            case "person":
                return this.person;
            case "start":
                return this.start;
            case "startTime":
                return this.startTime;
            case "title":
                return this.title;
            case "route":
                return this.route;
            case "spot":
                return this.spot;
            case "trip":
                return this.trip;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "end":
                this.end = (LocalDate)val;
                break;
            case "endTime":
                this.endTime = (LocalTime)val;
                break;
            case "person":
                this.person = (String)val;
                break;
            case "start":
                this.start = (LocalDate)val;
                break;
            case "startTime":
                this.startTime = (LocalTime)val;
                break;
            case "title":
                this.title = (String)val;
                break;
            case "route":
                this.route = val;
                break;
            case "spot":
                this.spot = val;
                break;
            case "trip":
                this.trip = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.end);
        out.writeObject(this.endTime);
        out.writeObject(this.person);
        out.writeObject(this.start);
        out.writeObject(this.startTime);
        out.writeObject(this.title);
        out.writeObject(this.route);
        out.writeObject(this.spot);
        out.writeObject(this.trip);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.end = (LocalDate)in.readObject();
        this.endTime = (LocalTime)in.readObject();
        this.person = (String)in.readObject();
        this.start = (LocalDate)in.readObject();
        this.startTime = (LocalTime)in.readObject();
        this.title = (String)in.readObject();
        this.route = in.readObject();
        this.spot = in.readObject();
        this.trip = in.readObject();
    }

}
