package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.DrivingRoute;
import vacation.data.RouteStop;

/**
 * Class _DrivingRoute was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrivingRoute extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<DrivingRoute> SELF = PropertyFactory.createSelf(DrivingRoute.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "DrivingRoute", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> COLOR = PropertyFactory.createString("color", String.class);
    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final NumericProperty<Integer> DISTANCE_KM = PropertyFactory.createNumeric("distanceKm", Integer.class);
    public static final NumericProperty<Integer> DURATION_MIN = PropertyFactory.createNumeric("durationMin", Integer.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final StringProperty<String> SLUG = PropertyFactory.createString("slug", String.class);
    public static final ListProperty<RouteStop> ROUTE_STOPS = PropertyFactory.createList("routeStops", RouteStop.class);

    protected String color;
    protected String description;
    protected int distanceKm;
    protected int durationMin;
    protected String name;
    protected String slug;

    protected Object routeStops;

    public void setColor(String color) {
        beforePropertyWrite("color", this.color, color);
        this.color = color;
    }

    public String color() {
        beforePropertyRead("color");
        return this.color;
    }

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String description() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setDistanceKm(int distanceKm) {
        beforePropertyWrite("distanceKm", this.distanceKm, distanceKm);
        this.distanceKm = distanceKm;
    }

    public int distanceKm() {
        beforePropertyRead("distanceKm");
        return this.distanceKm;
    }

    public void setDurationMin(int durationMin) {
        beforePropertyWrite("durationMin", this.durationMin, durationMin);
        this.durationMin = durationMin;
    }

    public int durationMin() {
        beforePropertyRead("durationMin");
        return this.durationMin;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String name() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setSlug(String slug) {
        beforePropertyWrite("slug", this.slug, slug);
        this.slug = slug;
    }

    public String slug() {
        beforePropertyRead("slug");
        return this.slug;
    }

    public void addToRouteStops(RouteStop obj) {
        addToManyTarget("routeStops", obj, true);
    }

    public void removeFromRouteStops(RouteStop obj) {
        removeToManyTarget("routeStops", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<RouteStop> routeStops() {
        return (List<RouteStop>)readProperty("routeStops");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "color":
                return this.color;
            case "description":
                return this.description;
            case "distanceKm":
                return this.distanceKm;
            case "durationMin":
                return this.durationMin;
            case "name":
                return this.name;
            case "slug":
                return this.slug;
            case "routeStops":
                return this.routeStops;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "color":
                this.color = (String)val;
                break;
            case "description":
                this.description = (String)val;
                break;
            case "distanceKm":
                this.distanceKm = val == null ? 0 : (int)val;
                break;
            case "durationMin":
                this.durationMin = val == null ? 0 : (int)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "slug":
                this.slug = (String)val;
                break;
            case "routeStops":
                this.routeStops = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.color);
        out.writeObject(this.description);
        out.writeInt(this.distanceKm);
        out.writeInt(this.durationMin);
        out.writeObject(this.name);
        out.writeObject(this.slug);
        out.writeObject(this.routeStops);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.color = (String)in.readObject();
        this.description = (String)in.readObject();
        this.distanceKm = in.readInt();
        this.durationMin = in.readInt();
        this.name = (String)in.readObject();
        this.slug = (String)in.readObject();
        this.routeStops = in.readObject();
    }

}
