package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.JournalEntry;
import vacation.data.Trip;

/**
 * Class _JournalEntry was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _JournalEntry extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<JournalEntry> SELF = PropertyFactory.createSelf(JournalEntry.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "JournalEntry", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> AUTHOR = PropertyFactory.createString("author", String.class);
    public static final DateProperty<LocalDate> DATE = PropertyFactory.createDate("date", LocalDate.class);
    public static final StringProperty<String> TEXT = PropertyFactory.createString("text", String.class);
    public static final StringProperty<String> TITLE = PropertyFactory.createString("title", String.class);
    public static final EntityProperty<Trip> TRIP = PropertyFactory.createEntity("trip", Trip.class);

    protected String author;
    protected LocalDate date;
    protected String text;
    protected String title;

    protected Object trip;

    public void setAuthor(String author) {
        beforePropertyWrite("author", this.author, author);
        this.author = author;
    }

    public String author() {
        beforePropertyRead("author");
        return this.author;
    }

    public void setDate(LocalDate date) {
        beforePropertyWrite("date", this.date, date);
        this.date = date;
    }

    public LocalDate date() {
        beforePropertyRead("date");
        return this.date;
    }

    public void setText(String text) {
        beforePropertyWrite("text", this.text, text);
        this.text = text;
    }

    public String text() {
        beforePropertyRead("text");
        return this.text;
    }

    public void setTitle(String title) {
        beforePropertyWrite("title", this.title, title);
        this.title = title;
    }

    public String title() {
        beforePropertyRead("title");
        return this.title;
    }

    public void setTrip(Trip trip) {
        setToOneTarget("trip", trip, true);
    }

    public Trip trip() {
        return (Trip)readProperty("trip");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "author":
                return this.author;
            case "date":
                return this.date;
            case "text":
                return this.text;
            case "title":
                return this.title;
            case "trip":
                return this.trip;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "author":
                this.author = (String)val;
                break;
            case "date":
                this.date = (LocalDate)val;
                break;
            case "text":
                this.text = (String)val;
                break;
            case "title":
                this.title = (String)val;
                break;
            case "trip":
                this.trip = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.author);
        out.writeObject(this.date);
        out.writeObject(this.text);
        out.writeObject(this.title);
        out.writeObject(this.trip);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.author = (String)in.readObject();
        this.date = (LocalDate)in.readObject();
        this.text = (String)in.readObject();
        this.title = (String)in.readObject();
        this.trip = in.readObject();
    }

}
