package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.Photo;
import vacation.data.Spot;
import vacation.data.Trip;

/**
 * Class _Photo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Photo extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Photo> SELF = PropertyFactory.createSelf(Photo.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "Photo", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> CAPTION = PropertyFactory.createString("caption", String.class);
    public static final StringProperty<String> FILENAME = PropertyFactory.createString("filename", String.class);
    public static final DateProperty<LocalDateTime> TAKEN = PropertyFactory.createDate("taken", LocalDateTime.class);
    public static final EntityProperty<Spot> SPOT = PropertyFactory.createEntity("spot", Spot.class);
    public static final EntityProperty<Trip> TRIP = PropertyFactory.createEntity("trip", Trip.class);

    protected String caption;
    protected String filename;
    protected LocalDateTime taken;

    protected Object spot;
    protected Object trip;

    public void setCaption(String caption) {
        beforePropertyWrite("caption", this.caption, caption);
        this.caption = caption;
    }

    public String caption() {
        beforePropertyRead("caption");
        return this.caption;
    }

    public void setFilename(String filename) {
        beforePropertyWrite("filename", this.filename, filename);
        this.filename = filename;
    }

    public String filename() {
        beforePropertyRead("filename");
        return this.filename;
    }

    public void setTaken(LocalDateTime taken) {
        beforePropertyWrite("taken", this.taken, taken);
        this.taken = taken;
    }

    public LocalDateTime taken() {
        beforePropertyRead("taken");
        return this.taken;
    }

    public void setSpot(Spot spot) {
        setToOneTarget("spot", spot, true);
    }

    public Spot spot() {
        return (Spot)readProperty("spot");
    }

    public void setTrip(Trip trip) {
        setToOneTarget("trip", trip, true);
    }

    public Trip trip() {
        return (Trip)readProperty("trip");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "caption":
                return this.caption;
            case "filename":
                return this.filename;
            case "taken":
                return this.taken;
            case "spot":
                return this.spot;
            case "trip":
                return this.trip;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "caption":
                this.caption = (String)val;
                break;
            case "filename":
                this.filename = (String)val;
                break;
            case "taken":
                this.taken = (LocalDateTime)val;
                break;
            case "spot":
                this.spot = val;
                break;
            case "trip":
                this.trip = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.caption);
        out.writeObject(this.filename);
        out.writeObject(this.taken);
        out.writeObject(this.spot);
        out.writeObject(this.trip);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.caption = (String)in.readObject();
        this.filename = (String)in.readObject();
        this.taken = (LocalDateTime)in.readObject();
        this.spot = in.readObject();
        this.trip = in.readObject();
    }

}
