package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;

import vacation.data.DrivingRoute;
import vacation.data.RouteStop;
import vacation.data.Spot;

/**
 * Class _RouteStop was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RouteStop extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<RouteStop> SELF = PropertyFactory.createSelf(RouteStop.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "RouteStop", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final NumericProperty<Integer> SORT_ORDER = PropertyFactory.createNumeric("sortOrder", Integer.class);
    public static final EntityProperty<DrivingRoute> ROUTE = PropertyFactory.createEntity("route", DrivingRoute.class);
    public static final EntityProperty<Spot> SPOT = PropertyFactory.createEntity("spot", Spot.class);

    protected int sortOrder;

    protected Object route;
    protected Object spot;

    public void setSortOrder(int sortOrder) {
        beforePropertyWrite("sortOrder", this.sortOrder, sortOrder);
        this.sortOrder = sortOrder;
    }

    public int sortOrder() {
        beforePropertyRead("sortOrder");
        return this.sortOrder;
    }

    public void setRoute(DrivingRoute route) {
        setToOneTarget("route", route, true);
    }

    public DrivingRoute route() {
        return (DrivingRoute)readProperty("route");
    }

    public void setSpot(Spot spot) {
        setToOneTarget("spot", spot, true);
    }

    public Spot spot() {
        return (Spot)readProperty("spot");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "sortOrder":
                return this.sortOrder;
            case "route":
                return this.route;
            case "spot":
                return this.spot;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "sortOrder":
                this.sortOrder = val == null ? 0 : (int)val;
                break;
            case "route":
                this.route = val;
                break;
            case "spot":
                this.spot = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeInt(this.sortOrder);
        out.writeObject(this.route);
        out.writeObject(this.spot);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.sortOrder = in.readInt();
        this.route = in.readObject();
        this.spot = in.readObject();
    }

}
