package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.CalendarEvent;
import vacation.data.Photo;
import vacation.data.RouteStop;
import vacation.data.Spot;
import vacation.data.Visit;

/**
 * Class _Spot was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Spot extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Spot> SELF = PropertyFactory.createSelf(Spot.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "Spot", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> CATEGORY = PropertyFactory.createString("category", String.class);
    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final StringProperty<String> IMAGE = PropertyFactory.createString("image", String.class);
    public static final NumericProperty<Double> LAT = PropertyFactory.createNumeric("lat", Double.class);
    public static final NumericProperty<Double> LON = PropertyFactory.createNumeric("lon", Double.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final StringProperty<String> SLUG = PropertyFactory.createString("slug", String.class);
    public static final StringProperty<String> URL = PropertyFactory.createString("url", String.class);
    public static final ListProperty<CalendarEvent> EVENTS = PropertyFactory.createList("events", CalendarEvent.class);
    public static final ListProperty<Photo> PHOTOS = PropertyFactory.createList("photos", Photo.class);
    public static final ListProperty<RouteStop> ROUTE_STOPS = PropertyFactory.createList("routeStops", RouteStop.class);
    public static final ListProperty<Visit> VISITS = PropertyFactory.createList("visits", Visit.class);

    protected String category;
    protected String description;
    protected String image;
    protected double lat;
    protected double lon;
    protected String name;
    protected String slug;
    protected String url;

    protected Object events;
    protected Object photos;
    protected Object routeStops;
    protected Object visits;

    public void setCategory(String category) {
        beforePropertyWrite("category", this.category, category);
        this.category = category;
    }

    public String category() {
        beforePropertyRead("category");
        return this.category;
    }

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String description() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setImage(String image) {
        beforePropertyWrite("image", this.image, image);
        this.image = image;
    }

    public String image() {
        beforePropertyRead("image");
        return this.image;
    }

    public void setLat(double lat) {
        beforePropertyWrite("lat", this.lat, lat);
        this.lat = lat;
    }

    public double lat() {
        beforePropertyRead("lat");
        return this.lat;
    }

    public void setLon(double lon) {
        beforePropertyWrite("lon", this.lon, lon);
        this.lon = lon;
    }

    public double lon() {
        beforePropertyRead("lon");
        return this.lon;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String name() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setSlug(String slug) {
        beforePropertyWrite("slug", this.slug, slug);
        this.slug = slug;
    }

    public String slug() {
        beforePropertyRead("slug");
        return this.slug;
    }

    public void setUrl(String url) {
        beforePropertyWrite("url", this.url, url);
        this.url = url;
    }

    public String url() {
        beforePropertyRead("url");
        return this.url;
    }

    public void addToEvents(CalendarEvent obj) {
        addToManyTarget("events", obj, true);
    }

    public void removeFromEvents(CalendarEvent obj) {
        removeToManyTarget("events", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<CalendarEvent> events() {
        return (List<CalendarEvent>)readProperty("events");
    }

    public void addToPhotos(Photo obj) {
        addToManyTarget("photos", obj, true);
    }

    public void removeFromPhotos(Photo obj) {
        removeToManyTarget("photos", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Photo> photos() {
        return (List<Photo>)readProperty("photos");
    }

    public void addToRouteStops(RouteStop obj) {
        addToManyTarget("routeStops", obj, true);
    }

    public void removeFromRouteStops(RouteStop obj) {
        removeToManyTarget("routeStops", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<RouteStop> routeStops() {
        return (List<RouteStop>)readProperty("routeStops");
    }

    public void addToVisits(Visit obj) {
        addToManyTarget("visits", obj, true);
    }

    public void removeFromVisits(Visit obj) {
        removeToManyTarget("visits", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Visit> visits() {
        return (List<Visit>)readProperty("visits");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "category":
                return this.category;
            case "description":
                return this.description;
            case "image":
                return this.image;
            case "lat":
                return this.lat;
            case "lon":
                return this.lon;
            case "name":
                return this.name;
            case "slug":
                return this.slug;
            case "url":
                return this.url;
            case "events":
                return this.events;
            case "photos":
                return this.photos;
            case "routeStops":
                return this.routeStops;
            case "visits":
                return this.visits;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "category":
                this.category = (String)val;
                break;
            case "description":
                this.description = (String)val;
                break;
            case "image":
                this.image = (String)val;
                break;
            case "lat":
                this.lat = val == null ? 0 : (double)val;
                break;
            case "lon":
                this.lon = val == null ? 0 : (double)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "slug":
                this.slug = (String)val;
                break;
            case "url":
                this.url = (String)val;
                break;
            case "events":
                this.events = val;
                break;
            case "photos":
                this.photos = val;
                break;
            case "routeStops":
                this.routeStops = val;
                break;
            case "visits":
                this.visits = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.category);
        out.writeObject(this.description);
        out.writeObject(this.image);
        out.writeDouble(this.lat);
        out.writeDouble(this.lon);
        out.writeObject(this.name);
        out.writeObject(this.slug);
        out.writeObject(this.url);
        out.writeObject(this.events);
        out.writeObject(this.photos);
        out.writeObject(this.routeStops);
        out.writeObject(this.visits);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.category = (String)in.readObject();
        this.description = (String)in.readObject();
        this.image = (String)in.readObject();
        this.lat = in.readDouble();
        this.lon = in.readDouble();
        this.name = (String)in.readObject();
        this.slug = (String)in.readObject();
        this.url = (String)in.readObject();
        this.events = in.readObject();
        this.photos = in.readObject();
        this.routeStops = in.readObject();
        this.visits = in.readObject();
    }

}
