package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.CalendarEvent;
import vacation.data.DrivingRoute;
import vacation.data.JournalEntry;
import vacation.data.Photo;
import vacation.data.Trip;
import vacation.data.Visit;

/**
 * Class _Trip was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Trip extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Trip> SELF = PropertyFactory.createSelf(Trip.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "Trip", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final DateProperty<LocalDate> END = PropertyFactory.createDate("end", LocalDate.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final StringProperty<String> SLUG = PropertyFactory.createString("slug", String.class);
    public static final DateProperty<LocalDate> START = PropertyFactory.createDate("start", LocalDate.class);
    public static final StringProperty<String> STATUS = PropertyFactory.createString("status", String.class);
    public static final ListProperty<CalendarEvent> EVENTS = PropertyFactory.createList("events", CalendarEvent.class);
    public static final ListProperty<JournalEntry> JOURNAL_ENTRIES = PropertyFactory.createList("journalEntries", JournalEntry.class);
    public static final ListProperty<Photo> PHOTOS = PropertyFactory.createList("photos", Photo.class);
    public static final ListProperty<DrivingRoute> ROUTES = PropertyFactory.createList("routes", DrivingRoute.class);
    public static final ListProperty<Visit> VISITS = PropertyFactory.createList("visits", Visit.class);

    protected String description;
    protected LocalDate end;
    protected String name;
    protected String slug;
    protected LocalDate start;
    protected String status;

    protected Object events;
    protected Object journalEntries;
    protected Object photos;
    protected Object routes;
    protected Object visits;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String description() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setEnd(LocalDate end) {
        beforePropertyWrite("end", this.end, end);
        this.end = end;
    }

    public LocalDate end() {
        beforePropertyRead("end");
        return this.end;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String name() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setSlug(String slug) {
        beforePropertyWrite("slug", this.slug, slug);
        this.slug = slug;
    }

    public String slug() {
        beforePropertyRead("slug");
        return this.slug;
    }

    public void setStart(LocalDate start) {
        beforePropertyWrite("start", this.start, start);
        this.start = start;
    }

    public LocalDate start() {
        beforePropertyRead("start");
        return this.start;
    }

    public void setStatus(String status) {
        beforePropertyWrite("status", this.status, status);
        this.status = status;
    }

    public String status() {
        beforePropertyRead("status");
        return this.status;
    }

    public void addToEvents(CalendarEvent obj) {
        addToManyTarget("events", obj, true);
    }

    public void removeFromEvents(CalendarEvent obj) {
        removeToManyTarget("events", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<CalendarEvent> events() {
        return (List<CalendarEvent>)readProperty("events");
    }

    public void addToJournalEntries(JournalEntry obj) {
        addToManyTarget("journalEntries", obj, true);
    }

    public void removeFromJournalEntries(JournalEntry obj) {
        removeToManyTarget("journalEntries", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<JournalEntry> journalEntries() {
        return (List<JournalEntry>)readProperty("journalEntries");
    }

    public void addToPhotos(Photo obj) {
        addToManyTarget("photos", obj, true);
    }

    public void removeFromPhotos(Photo obj) {
        removeToManyTarget("photos", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Photo> photos() {
        return (List<Photo>)readProperty("photos");
    }

    public void addToRoutes(DrivingRoute obj) {
        addToManyTarget("routes", obj, true);
    }

    public void removeFromRoutes(DrivingRoute obj) {
        removeToManyTarget("routes", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<DrivingRoute> routes() {
        return (List<DrivingRoute>)readProperty("routes");
    }

    public void addToVisits(Visit obj) {
        addToManyTarget("visits", obj, true);
    }

    public void removeFromVisits(Visit obj) {
        removeToManyTarget("visits", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Visit> visits() {
        return (List<Visit>)readProperty("visits");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "end":
                return this.end;
            case "name":
                return this.name;
            case "slug":
                return this.slug;
            case "start":
                return this.start;
            case "status":
                return this.status;
            case "events":
                return this.events;
            case "journalEntries":
                return this.journalEntries;
            case "photos":
                return this.photos;
            case "routes":
                return this.routes;
            case "visits":
                return this.visits;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "end":
                this.end = (LocalDate)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "slug":
                this.slug = (String)val;
                break;
            case "start":
                this.start = (LocalDate)val;
                break;
            case "status":
                this.status = (String)val;
                break;
            case "events":
                this.events = val;
                break;
            case "journalEntries":
                this.journalEntries = val;
                break;
            case "photos":
                this.photos = val;
                break;
            case "routes":
                this.routes = val;
                break;
            case "visits":
                this.visits = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.end);
        out.writeObject(this.name);
        out.writeObject(this.slug);
        out.writeObject(this.start);
        out.writeObject(this.status);
        out.writeObject(this.events);
        out.writeObject(this.journalEntries);
        out.writeObject(this.photos);
        out.writeObject(this.routes);
        out.writeObject(this.visits);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.end = (LocalDate)in.readObject();
        this.name = (String)in.readObject();
        this.slug = (String)in.readObject();
        this.start = (LocalDate)in.readObject();
        this.status = (String)in.readObject();
        this.events = in.readObject();
        this.journalEntries = in.readObject();
        this.photos = in.readObject();
        this.routes = in.readObject();
        this.visits = in.readObject();
    }

}
