package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.Trip;
import vacation.data.TripEvent;

/**
 * Class _TripEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TripEvent extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<TripEvent> SELF = PropertyFactory.createSelf(TripEvent.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "TripEvent", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final DateProperty<LocalDate> END = PropertyFactory.createDate("end", LocalDate.class);
    public static final DateProperty<LocalDate> START = PropertyFactory.createDate("start", LocalDate.class);
    public static final StringProperty<String> TITLE = PropertyFactory.createString("title", String.class);
    public static final EntityProperty<Trip> TRIP = PropertyFactory.createEntity("trip", Trip.class);

    protected String description;
    protected LocalDate end;
    protected LocalDate start;
    protected String title;

    protected Object trip;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String description() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setEnd(LocalDate end) {
        beforePropertyWrite("end", this.end, end);
        this.end = end;
    }

    public LocalDate end() {
        beforePropertyRead("end");
        return this.end;
    }

    public void setStart(LocalDate start) {
        beforePropertyWrite("start", this.start, start);
        this.start = start;
    }

    public LocalDate start() {
        beforePropertyRead("start");
        return this.start;
    }

    public void setTitle(String title) {
        beforePropertyWrite("title", this.title, title);
        this.title = title;
    }

    public String title() {
        beforePropertyRead("title");
        return this.title;
    }

    public void setTrip(Trip trip) {
        setToOneTarget("trip", trip, true);
    }

    public Trip trip() {
        return (Trip)readProperty("trip");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "end":
                return this.end;
            case "start":
                return this.start;
            case "title":
                return this.title;
            case "trip":
                return this.trip;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "end":
                this.end = (LocalDate)val;
                break;
            case "start":
                this.start = (LocalDate)val;
                break;
            case "title":
                this.title = (String)val;
                break;
            case "trip":
                this.trip = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.end);
        out.writeObject(this.start);
        out.writeObject(this.title);
        out.writeObject(this.trip);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.end = (LocalDate)in.readObject();
        this.start = (LocalDate)in.readObject();
        this.title = (String)in.readObject();
        this.trip = in.readObject();
    }

}
