package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.Trip;
import vacation.data.TripEvent;

/**
 * Class _Trip was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Trip extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Trip> SELF = PropertyFactory.createSelf(Trip.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "Trip", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final DateProperty<LocalDate> END = PropertyFactory.createDate("end", LocalDate.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final DateProperty<LocalDate> START = PropertyFactory.createDate("start", LocalDate.class);
    public static final ListProperty<TripEvent> EVENTS = PropertyFactory.createList("events", TripEvent.class);

    protected LocalDate end;
    protected String name;
    protected LocalDate start;

    protected Object events;

    public void setEnd(LocalDate end) {
        beforePropertyWrite("end", this.end, end);
        this.end = end;
    }

    public LocalDate end() {
        beforePropertyRead("end");
        return this.end;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String name() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setStart(LocalDate start) {
        beforePropertyWrite("start", this.start, start);
        this.start = start;
    }

    public LocalDate start() {
        beforePropertyRead("start");
        return this.start;
    }

    public void addToEvents(TripEvent obj) {
        addToManyTarget("events", obj, true);
    }

    public void removeFromEvents(TripEvent obj) {
        removeToManyTarget("events", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<TripEvent> events() {
        return (List<TripEvent>)readProperty("events");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "end":
                return this.end;
            case "name":
                return this.name;
            case "start":
                return this.start;
            case "events":
                return this.events;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "end":
                this.end = (LocalDate)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "start":
                this.start = (LocalDate)val;
                break;
            case "events":
                this.events = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.end);
        out.writeObject(this.name);
        out.writeObject(this.start);
        out.writeObject(this.events);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.end = (LocalDate)in.readObject();
        this.name = (String)in.readObject();
        this.start = (LocalDate)in.readObject();
        this.events = in.readObject();
    }

}
