package vacation.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import vacation.data.Spot;
import vacation.data.Trip;
import vacation.data.Visit;

/**
 * Class _Visit was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Visit extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Visit> SELF = PropertyFactory.createSelf(Visit.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "Visit", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final DateProperty<LocalDate> DATE = PropertyFactory.createDate("date", LocalDate.class);
    public static final StringProperty<String> NOTES = PropertyFactory.createString("notes", String.class);
    public static final StringProperty<String> STATUS = PropertyFactory.createString("status", String.class);
    public static final EntityProperty<Spot> SPOT = PropertyFactory.createEntity("spot", Spot.class);
    public static final EntityProperty<Trip> TRIP = PropertyFactory.createEntity("trip", Trip.class);

    protected LocalDate date;
    protected String notes;
    protected String status;

    protected Object spot;
    protected Object trip;

    public void setDate(LocalDate date) {
        beforePropertyWrite("date", this.date, date);
        this.date = date;
    }

    public LocalDate date() {
        beforePropertyRead("date");
        return this.date;
    }

    public void setNotes(String notes) {
        beforePropertyWrite("notes", this.notes, notes);
        this.notes = notes;
    }

    public String notes() {
        beforePropertyRead("notes");
        return this.notes;
    }

    public void setStatus(String status) {
        beforePropertyWrite("status", this.status, status);
        this.status = status;
    }

    public String status() {
        beforePropertyRead("status");
        return this.status;
    }

    public void setSpot(Spot spot) {
        setToOneTarget("spot", spot, true);
    }

    public Spot spot() {
        return (Spot)readProperty("spot");
    }

    public void setTrip(Trip trip) {
        setToOneTarget("trip", trip, true);
    }

    public Trip trip() {
        return (Trip)readProperty("trip");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "date":
                return this.date;
            case "notes":
                return this.notes;
            case "status":
                return this.status;
            case "spot":
                return this.spot;
            case "trip":
                return this.trip;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "date":
                this.date = (LocalDate)val;
                break;
            case "notes":
                this.notes = (String)val;
                break;
            case "status":
                this.status = (String)val;
                break;
            case "spot":
                this.spot = val;
                break;
            case "trip":
                this.trip = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.date);
        out.writeObject(this.notes);
        out.writeObject(this.status);
        out.writeObject(this.spot);
        out.writeObject(this.trip);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.date = (LocalDate)in.readObject();
        this.notes = (String)in.readObject();
        this.status = (String)in.readObject();
        this.spot = in.readObject();
        this.trip = in.readObject();
    }

}
